### ISSUE TITLE
Issue with charging battery

### ISSUE THREAD

**Issue by dalefrancis88** [Heltec-Aaron-Lee/WiFi_Kit_series#57]
I bought the board from amazon and i'm liking it so far, but one of the key reasons for buying it was the battery connecter and charging. I have four batteries and three boards and i've tested all batteries on two boards and while the board recognized there is a battery installed it does not seem to be charging the battery. Wierd thing is the battery is a little warm when i pick it up which generally means it's been charging.

Am i missing something with this board, how do i get the battery to charge and the board to run off battery?

**Comment by ArnauldDev** [comment]
To charge the battery and operate the card, just [connect the battery to the connector under the card](http://www.heltec.cn/wifi-lora-32/?lang=en) and that's it, when you connect the card to a USB port then the LED "BAT" orange turns on ;-)
For my part, I would like to know the reference of the battery connector in order to weld a 18650?
